//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/SpaceCombatKit/UniversalVehicleCombat/InputSystem/GeneralInputAsset.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GeneralInputAsset: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GeneralInputAsset()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GeneralInputAsset"",
    ""maps"": [
        {
            ""name"": ""General Controls"",
            ""id"": ""bb585eb7-c211-4d88-bb77-1af054e5dd2c"",
            ""actions"": [
                {
                    ""name"": ""Pause Menu"",
                    ""type"": ""Button"",
                    ""id"": ""3535a8b6-de8c-44d4-9d91-80e657ddd5f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""f181701c-36e8-488e-b5c6-da065fb81075"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse Position"",
                    ""type"": ""Value"",
                    ""id"": ""679a9914-ed25-4bc9-813e-f8cf2843fd5a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse Delta"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1f743bad-b2bd-4354-ad7b-f5b1dea07abb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ac5f2434-33c3-4c39-86be-068e8eb5bc3b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Pause Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64afd738-3515-40a9-9dd0-85e3f9f0bf13"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48cf29cf-8854-4da3-ad01-49d76240ba39"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Mouse Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fce23e03-6281-4d1d-bc20-04bbf7e068b6"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Mouse Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""6a7b1f27-89f3-4097-aff8-5dc9db9c3cac"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=15,y=15)"",
                    ""groups"": """",
                    ""action"": ""Mouse Delta"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""98baad09-1fa5-4877-8095-60368939cce9"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0c64fb13-9129-420f-bff1-6bfac4a8c314"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ef253d25-2784-43c8-b24d-5c0716a647bf"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ca64372c-144f-4d1a-aa90-8027a7bdd1f7"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""61dacdf7-d630-432b-a5c3-8d5bd6fe327d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29b3fc70-e61c-4eff-b0ef-01799ac29247"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Targeting Controls"",
            ""id"": ""7ddec75a-5f03-481a-8770-9c616f49810d"",
            ""actions"": [
                {
                    ""name"": ""Target Next"",
                    ""type"": ""Button"",
                    ""id"": ""f9880903-5205-4846-abe4-a136a6ae0de0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Target Previous"",
                    ""type"": ""Button"",
                    ""id"": ""37a3c2de-4051-4511-878d-2d37e633555b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Target Nearest"",
                    ""type"": ""Button"",
                    ""id"": ""684430e0-f190-4cb4-a76d-2e31fc978424"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Target Front"",
                    ""type"": ""Button"",
                    ""id"": ""0b114351-80b2-45c9-86b1-9f8fa516e23b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3337a3d2-44e0-4a12-be15-43b8c591649c"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Target Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b84ea82f-e6ea-400f-9f74-29ad7ddb6a17"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Target Previous"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c931802-3f47-47fb-a7e7-a5c4d00e631e"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Target Nearest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b0abe5b-fb56-493b-9f1e-58442ae09d32"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Target Front"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera Controls"",
            ""id"": ""6dcf97a5-c9f1-4b33-af21-d6b77b5d0d6e"",
            ""actions"": [
                {
                    ""name"": ""Cycle Camera View Forward"",
                    ""type"": ""Button"",
                    ""id"": ""bd01cca4-0e84-4f44-bdc6-ae5eb8131966"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cycle Camera View Back"",
                    ""type"": ""Button"",
                    ""id"": ""8f98e45a-b3fd-4fb7-8314-5aedbed2b04e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Free Look Mode"",
                    ""type"": ""Button"",
                    ""id"": ""3d696e79-978c-4d04-af8d-959f9292816b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4f039296-9aa9-40a8-8eda-0a28611dc3ab"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Cycle Camera View Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edb21f15-e522-4eba-a780-96c7244720c3"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cycle Camera View Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1522403-512c-4699-98f4-695bee30cd36"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Cycle Camera View Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac15e597-2ccc-4fb0-8f26-aba26677205f"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Free Look Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Weapon Controls"",
            ""id"": ""eb4a4066-a61c-46c3-8398-a80716916c7a"",
            ""actions"": [
                {
                    ""name"": ""Fire Primary"",
                    ""type"": ""Button"",
                    ""id"": ""91cde11e-4ede-4d96-8542-dba35a41c0b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire Secondary"",
                    ""type"": ""Button"",
                    ""id"": ""c3f05d08-72e0-479a-98eb-94eeab8ca1fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bbfd9e05-66a9-4070-a581-e5ef76fc62ac"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Fire Primary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf93514e-2938-4a92-a728-4ade5e481554"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Fire Primary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34b02c37-7f66-4ae7-ad21-99856422b177"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Fire Secondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f057a00f-ada5-4d39-a346-e260c2c23963"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Fire Secondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""MouseKeyboard"",
            ""bindingGroup"": ""MouseKeyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // General Controls
        m_GeneralControls = asset.FindActionMap("General Controls", throwIfNotFound: true);
        m_GeneralControls_PauseMenu = m_GeneralControls.FindAction("Pause Menu", throwIfNotFound: true);
        m_GeneralControls_Use = m_GeneralControls.FindAction("Use", throwIfNotFound: true);
        m_GeneralControls_MousePosition = m_GeneralControls.FindAction("Mouse Position", throwIfNotFound: true);
        m_GeneralControls_MouseDelta = m_GeneralControls.FindAction("Mouse Delta", throwIfNotFound: true);
        // Targeting Controls
        m_TargetingControls = asset.FindActionMap("Targeting Controls", throwIfNotFound: true);
        m_TargetingControls_TargetNext = m_TargetingControls.FindAction("Target Next", throwIfNotFound: true);
        m_TargetingControls_TargetPrevious = m_TargetingControls.FindAction("Target Previous", throwIfNotFound: true);
        m_TargetingControls_TargetNearest = m_TargetingControls.FindAction("Target Nearest", throwIfNotFound: true);
        m_TargetingControls_TargetFront = m_TargetingControls.FindAction("Target Front", throwIfNotFound: true);
        // Camera Controls
        m_CameraControls = asset.FindActionMap("Camera Controls", throwIfNotFound: true);
        m_CameraControls_CycleCameraViewForward = m_CameraControls.FindAction("Cycle Camera View Forward", throwIfNotFound: true);
        m_CameraControls_CycleCameraViewBack = m_CameraControls.FindAction("Cycle Camera View Back", throwIfNotFound: true);
        m_CameraControls_FreeLookMode = m_CameraControls.FindAction("Free Look Mode", throwIfNotFound: true);
        // Weapon Controls
        m_WeaponControls = asset.FindActionMap("Weapon Controls", throwIfNotFound: true);
        m_WeaponControls_FirePrimary = m_WeaponControls.FindAction("Fire Primary", throwIfNotFound: true);
        m_WeaponControls_FireSecondary = m_WeaponControls.FindAction("Fire Secondary", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // General Controls
    private readonly InputActionMap m_GeneralControls;
    private List<IGeneralControlsActions> m_GeneralControlsActionsCallbackInterfaces = new List<IGeneralControlsActions>();
    private readonly InputAction m_GeneralControls_PauseMenu;
    private readonly InputAction m_GeneralControls_Use;
    private readonly InputAction m_GeneralControls_MousePosition;
    private readonly InputAction m_GeneralControls_MouseDelta;
    public struct GeneralControlsActions
    {
        private @GeneralInputAsset m_Wrapper;
        public GeneralControlsActions(@GeneralInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @PauseMenu => m_Wrapper.m_GeneralControls_PauseMenu;
        public InputAction @Use => m_Wrapper.m_GeneralControls_Use;
        public InputAction @MousePosition => m_Wrapper.m_GeneralControls_MousePosition;
        public InputAction @MouseDelta => m_Wrapper.m_GeneralControls_MouseDelta;
        public InputActionMap Get() { return m_Wrapper.m_GeneralControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralControlsActions set) { return set.Get(); }
        public void AddCallbacks(IGeneralControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_GeneralControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GeneralControlsActionsCallbackInterfaces.Add(instance);
            @PauseMenu.started += instance.OnPauseMenu;
            @PauseMenu.performed += instance.OnPauseMenu;
            @PauseMenu.canceled += instance.OnPauseMenu;
            @Use.started += instance.OnUse;
            @Use.performed += instance.OnUse;
            @Use.canceled += instance.OnUse;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
        }

        private void UnregisterCallbacks(IGeneralControlsActions instance)
        {
            @PauseMenu.started -= instance.OnPauseMenu;
            @PauseMenu.performed -= instance.OnPauseMenu;
            @PauseMenu.canceled -= instance.OnPauseMenu;
            @Use.started -= instance.OnUse;
            @Use.performed -= instance.OnUse;
            @Use.canceled -= instance.OnUse;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
        }

        public void RemoveCallbacks(IGeneralControlsActions instance)
        {
            if (m_Wrapper.m_GeneralControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGeneralControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_GeneralControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GeneralControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GeneralControlsActions @GeneralControls => new GeneralControlsActions(this);

    // Targeting Controls
    private readonly InputActionMap m_TargetingControls;
    private List<ITargetingControlsActions> m_TargetingControlsActionsCallbackInterfaces = new List<ITargetingControlsActions>();
    private readonly InputAction m_TargetingControls_TargetNext;
    private readonly InputAction m_TargetingControls_TargetPrevious;
    private readonly InputAction m_TargetingControls_TargetNearest;
    private readonly InputAction m_TargetingControls_TargetFront;
    public struct TargetingControlsActions
    {
        private @GeneralInputAsset m_Wrapper;
        public TargetingControlsActions(@GeneralInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @TargetNext => m_Wrapper.m_TargetingControls_TargetNext;
        public InputAction @TargetPrevious => m_Wrapper.m_TargetingControls_TargetPrevious;
        public InputAction @TargetNearest => m_Wrapper.m_TargetingControls_TargetNearest;
        public InputAction @TargetFront => m_Wrapper.m_TargetingControls_TargetFront;
        public InputActionMap Get() { return m_Wrapper.m_TargetingControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TargetingControlsActions set) { return set.Get(); }
        public void AddCallbacks(ITargetingControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_TargetingControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TargetingControlsActionsCallbackInterfaces.Add(instance);
            @TargetNext.started += instance.OnTargetNext;
            @TargetNext.performed += instance.OnTargetNext;
            @TargetNext.canceled += instance.OnTargetNext;
            @TargetPrevious.started += instance.OnTargetPrevious;
            @TargetPrevious.performed += instance.OnTargetPrevious;
            @TargetPrevious.canceled += instance.OnTargetPrevious;
            @TargetNearest.started += instance.OnTargetNearest;
            @TargetNearest.performed += instance.OnTargetNearest;
            @TargetNearest.canceled += instance.OnTargetNearest;
            @TargetFront.started += instance.OnTargetFront;
            @TargetFront.performed += instance.OnTargetFront;
            @TargetFront.canceled += instance.OnTargetFront;
        }

        private void UnregisterCallbacks(ITargetingControlsActions instance)
        {
            @TargetNext.started -= instance.OnTargetNext;
            @TargetNext.performed -= instance.OnTargetNext;
            @TargetNext.canceled -= instance.OnTargetNext;
            @TargetPrevious.started -= instance.OnTargetPrevious;
            @TargetPrevious.performed -= instance.OnTargetPrevious;
            @TargetPrevious.canceled -= instance.OnTargetPrevious;
            @TargetNearest.started -= instance.OnTargetNearest;
            @TargetNearest.performed -= instance.OnTargetNearest;
            @TargetNearest.canceled -= instance.OnTargetNearest;
            @TargetFront.started -= instance.OnTargetFront;
            @TargetFront.performed -= instance.OnTargetFront;
            @TargetFront.canceled -= instance.OnTargetFront;
        }

        public void RemoveCallbacks(ITargetingControlsActions instance)
        {
            if (m_Wrapper.m_TargetingControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITargetingControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_TargetingControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TargetingControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TargetingControlsActions @TargetingControls => new TargetingControlsActions(this);

    // Camera Controls
    private readonly InputActionMap m_CameraControls;
    private List<ICameraControlsActions> m_CameraControlsActionsCallbackInterfaces = new List<ICameraControlsActions>();
    private readonly InputAction m_CameraControls_CycleCameraViewForward;
    private readonly InputAction m_CameraControls_CycleCameraViewBack;
    private readonly InputAction m_CameraControls_FreeLookMode;
    public struct CameraControlsActions
    {
        private @GeneralInputAsset m_Wrapper;
        public CameraControlsActions(@GeneralInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @CycleCameraViewForward => m_Wrapper.m_CameraControls_CycleCameraViewForward;
        public InputAction @CycleCameraViewBack => m_Wrapper.m_CameraControls_CycleCameraViewBack;
        public InputAction @FreeLookMode => m_Wrapper.m_CameraControls_FreeLookMode;
        public InputActionMap Get() { return m_Wrapper.m_CameraControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICameraControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Add(instance);
            @CycleCameraViewForward.started += instance.OnCycleCameraViewForward;
            @CycleCameraViewForward.performed += instance.OnCycleCameraViewForward;
            @CycleCameraViewForward.canceled += instance.OnCycleCameraViewForward;
            @CycleCameraViewBack.started += instance.OnCycleCameraViewBack;
            @CycleCameraViewBack.performed += instance.OnCycleCameraViewBack;
            @CycleCameraViewBack.canceled += instance.OnCycleCameraViewBack;
            @FreeLookMode.started += instance.OnFreeLookMode;
            @FreeLookMode.performed += instance.OnFreeLookMode;
            @FreeLookMode.canceled += instance.OnFreeLookMode;
        }

        private void UnregisterCallbacks(ICameraControlsActions instance)
        {
            @CycleCameraViewForward.started -= instance.OnCycleCameraViewForward;
            @CycleCameraViewForward.performed -= instance.OnCycleCameraViewForward;
            @CycleCameraViewForward.canceled -= instance.OnCycleCameraViewForward;
            @CycleCameraViewBack.started -= instance.OnCycleCameraViewBack;
            @CycleCameraViewBack.performed -= instance.OnCycleCameraViewBack;
            @CycleCameraViewBack.canceled -= instance.OnCycleCameraViewBack;
            @FreeLookMode.started -= instance.OnFreeLookMode;
            @FreeLookMode.performed -= instance.OnFreeLookMode;
            @FreeLookMode.canceled -= instance.OnFreeLookMode;
        }

        public void RemoveCallbacks(ICameraControlsActions instance)
        {
            if (m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraControlsActions @CameraControls => new CameraControlsActions(this);

    // Weapon Controls
    private readonly InputActionMap m_WeaponControls;
    private List<IWeaponControlsActions> m_WeaponControlsActionsCallbackInterfaces = new List<IWeaponControlsActions>();
    private readonly InputAction m_WeaponControls_FirePrimary;
    private readonly InputAction m_WeaponControls_FireSecondary;
    public struct WeaponControlsActions
    {
        private @GeneralInputAsset m_Wrapper;
        public WeaponControlsActions(@GeneralInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @FirePrimary => m_Wrapper.m_WeaponControls_FirePrimary;
        public InputAction @FireSecondary => m_Wrapper.m_WeaponControls_FireSecondary;
        public InputActionMap Get() { return m_Wrapper.m_WeaponControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WeaponControlsActions set) { return set.Get(); }
        public void AddCallbacks(IWeaponControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_WeaponControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WeaponControlsActionsCallbackInterfaces.Add(instance);
            @FirePrimary.started += instance.OnFirePrimary;
            @FirePrimary.performed += instance.OnFirePrimary;
            @FirePrimary.canceled += instance.OnFirePrimary;
            @FireSecondary.started += instance.OnFireSecondary;
            @FireSecondary.performed += instance.OnFireSecondary;
            @FireSecondary.canceled += instance.OnFireSecondary;
        }

        private void UnregisterCallbacks(IWeaponControlsActions instance)
        {
            @FirePrimary.started -= instance.OnFirePrimary;
            @FirePrimary.performed -= instance.OnFirePrimary;
            @FirePrimary.canceled -= instance.OnFirePrimary;
            @FireSecondary.started -= instance.OnFireSecondary;
            @FireSecondary.performed -= instance.OnFireSecondary;
            @FireSecondary.canceled -= instance.OnFireSecondary;
        }

        public void RemoveCallbacks(IWeaponControlsActions instance)
        {
            if (m_Wrapper.m_WeaponControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWeaponControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_WeaponControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WeaponControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WeaponControlsActions @WeaponControls => new WeaponControlsActions(this);
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("MouseKeyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IGeneralControlsActions
    {
        void OnPauseMenu(InputAction.CallbackContext context);
        void OnUse(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
    }
    public interface ITargetingControlsActions
    {
        void OnTargetNext(InputAction.CallbackContext context);
        void OnTargetPrevious(InputAction.CallbackContext context);
        void OnTargetNearest(InputAction.CallbackContext context);
        void OnTargetFront(InputAction.CallbackContext context);
    }
    public interface ICameraControlsActions
    {
        void OnCycleCameraViewForward(InputAction.CallbackContext context);
        void OnCycleCameraViewBack(InputAction.CallbackContext context);
        void OnFreeLookMode(InputAction.CallbackContext context);
    }
    public interface IWeaponControlsActions
    {
        void OnFirePrimary(InputAction.CallbackContext context);
        void OnFireSecondary(InputAction.CallbackContext context);
    }
}
